### ISSUE TITLE
Task: build/refine the login feature

### ISSUE THREAD

**Issue by hgiordano888** [Allen-ISD-Computer-Science/REPO_ModelScheduler_2024#12]
In order to retain the progress of schedules and have multiple schedules in one space, there should be a way to login to a profile and view all the schedules. The login feature should include a database that stores all the login information and a way to access and verify accounts.

Support Story #6

**Comment by Richard-Jang** [comment]
I need another week to correctly implement the login feature and database.

**Comment by t1np0t** [comment]
I need another week to finalize the new UI design for the login page

**Comment by Swific** [comment]
The UI Draft is finished but I aso need another week to finish the new revamped UI login page.
