### ISSUE TITLE
create scheduler page mockup (in figma)

### ISSUE THREAD

**Issue by lucas-m-pham** [Allen-ISD-Computer-Science/REPO_ModelScheduler_2024#16]
create a mock up for the layout and design of the web pages for the model scheduler site.

**Comment by hgiordano888** [comment]
finished a first pass design and pushed it. will revise over the weekend 👍

**Comment by hgiordano888** [comment]
Will be working on this for the majority of next week as there are more pages to design

**Comment by lucas-m-pham** [comment]
Made commit 1004df19aa2ab51acac558c29da360e2047632ac. Uploaded png file of the mock up of the login page. mock up not final is will likely be heavily changed in terms of design, but they layout will likely be set as is right now.
