### ISSUE TITLE
Task: Conflict Detector

### ISSUE THREAD

**Issue by Richard-Jang** [Allen-ISD-Computer-Science/REPO_ModelScheduler_2024#17]
What are the possible scheduling conflicts between AHS, STEAM, and CTC classes?

Supports Story #4

**Comment by t1np0t** [comment]
Possible scheduling conflicts:

- 1st period at AHS and 2nd/5th period at STEAM/CTC (Times overlap)
- 8th period at AHS and 4th/7th period at STEAM/CTC (Times overlap)
- Two block privileges on the same day
- 1st and 8th privilege and a block privilege
- 3rd and 6th privilege periods (Can't have privilege periods during lunch periods)
- Classes where periods are preset (Ex: Orchestra, band, choir)
