### ISSUE TITLE
Task - FAQ

### ISSUE THREAD

**Issue by hgiordano888** [Allen-ISD-Computer-Science/REPO_ModelScheduler_2024#21]
Make an FAQ page

**Comment by hgiordano888** [comment]
was unable to complete this week due to confusion around assignments and other school commitments. will push to next sprint and complete along with the homepage planning

**Comment by Reynard-G** [comment]
Done w/ cd6ed00c8b778c1b2ec42c24becd8b39b0041af5

More questions/answers can be added at a later time
