### ISSUE TITLE
Story: Conflict Checker

### ISSUE THREAD

**Issue by Richard-Jang** [Allen-ISD-Computer-Science/REPO_ModelScheduler_2024#4]
As a student who hasn't created a schedule or is unfamiliar to creating a schedule, I want my classes to not have a scheduling conflict when creating my schedule, so I won't enter a faulty schedule into arena and not realize it.

Scheduling Rules:
- Privilege periods cannot be on the following:
  - 1st and 8th and block period (2nd, 4th, 5th, or 7th)
  - Two block periods:
    - A-day (2nd and 4th)
    - B-day (5th and 7th)
- AHS, STEAM, and CTC classes cannot have overlapping times.

**Comment by Reynard-G** [comment]
Finished w/ 87854fc81cf55feca212597266bb082ea38704b2
