### ISSUE TITLE
Story: Mobile Support

### ISSUE THREAD

**Issue by Richard-Jang** [Allen-ISD-Computer-Science/REPO_ModelScheduler_2024#7]
Little Timmy broke his Chromebook during sophomore year and can't get a new one. He is forced to use the Model Scheduler app on his phone. He needs the website to be mobile-friendly based on the dimensions of the device he is using without impairing his ability to use the website just as if he was on PC.

**Comment by Reynard-G** [comment]
Partially done, but will not continue. User is warned if screen is too small.
